language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-coffee-ember' ]; then cd .. && eval "mv $currentfolder generator-coffee-ember" && cd generator-coffee-ember; fi

